### ISSUE TITLE
Error when: rake db:migrate_plugins

### ISSUE THREAD

**Issue by supergarotinho** [Tide/redmine_menu_links#1]
Because of the following line on the init.rb of the plugin:

MenuLink.show

The following error appear when trying to migrate_plugins:
(in /home/gneuro/public_html/labs)
*\* Invoke db:migrate_plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Mysql::Error: Table 'gneuro_redmine.menu_links' doesn't exist: SELECT \* FROM `menu_links`
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract_adapter.rb:219:in `log'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/mysql_adapter.rb:323:in`execute'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/mysql_adapter.rb:608:in `select'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in`select_all_without_query_cache'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:62:in `select_all'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:661:in`find_by_sql'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:1548:in `find_every'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in`find'
/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
/home/gneuro/public_html/labs/vendor/plugins/redmine_menu_links/app/models/menu_link.rb:21:in`each_enabled_link'
/home/gneuro/public_html/labs/vendor/plugins/redmine_menu_links/app/models/menu_link.rb:33:in `show'
/home/gneuro/public_html/labs/vendor/plugins/redmine_menu_links/init.rb:15:in`evaluate_init_rb'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb:158:in `evaluate_init_rb'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/kernel/reporting.rb:11:in`silence_warnings'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb:154:in `evaluate_init_rb'

Commenting the line, i could migrate_plugins. But, i think that you must find a better way to do that.

Thanks

**Comment by Tide** [comment]
I believe this is solved now.  See if the new version works for you.
