### ISSUE TITLE
Error when entering on the menu_links config at Administration

### ISSUE THREAD

**Issue by supergarotinho** [Tide/redmine_menu_links#2]
Processing MenuLinksController#index (for 143.54.13.224 at 2010-04-12 14:07:36) [GET]
  Parameters: {"action"=>"index", "controller"=>"menu_links"}
Rendering template within layouts/base
Rendering menu_links/index

ActionView::TemplateError (undefined method `checked_image' for #ActionView::Base:0xb6de0e98) on line #18 of vendor/plugins/redmine_menu_links/app/views/menu_links/index.html.erb:
15: <% for link in @menu_links %>
16:   <tr class="<%= cycle("odd", "even") %>">
17:   <td><%= link_to link.name, :action => 'edit', :id => link %></td>
18:   <td align="center"><%= checked_image link.is_enabled %></td>
19:   <td align="center" style="width:15%;"><%= reorder_links('menu_link', {:action => 'update', :id => link}) %></td>
20:   <td class="buttons">
21:     <%= link_to(l(:button_delete), { :action => 'destroy', :id => link },

```
vendor/plugins/redmine_menu_links/app/views/menu_links/index.html.erb:18
vendor/plugins/redmine_menu_links/app/views/menu_links/index.html.erb:15:in `each'
vendor/plugins/redmine_menu_links/app/views/menu_links/index.html.erb:15
passenger (2.2.5) lib/phusion_passenger/rack/request_handler.rb:95:in `process_request'
passenger (2.2.5) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
passenger (2.2.5) lib/phusion_passenger/railz/application_spawner.rb:378:in `start_request_handler'
passenger (2.2.5) lib/phusion_passenger/railz/application_spawner.rb:336:in `handle_spawn_application'
passenger (2.2.5) lib/phusion_passenger/utils.rb:183:in `safe_fork'
passenger (2.2.5) lib/phusion_passenger/railz/application_spawner.rb:334:in `handle_spawn_application'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:163:in `start'
passenger (2.2.5) lib/phusion_passenger/railz/application_spawner.rb:213:in `start'
passenger (2.2.5) lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
passenger (2.2.5) lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
passenger (2.2.5) lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
passenger (2.2.5) lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
passenger (2.2.5) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (2.2.5) lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
passenger (2.2.5) lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
passenger (2.2.5) lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
passenger (2.2.5) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
```

Rendering /home/gneuro/public_html/labs/public/500.html (500 Internal Server Error)

**Comment by Tide** [comment]
Not sure on that one.  I have changed the code a bit.  See if the new version fixes this please.

**Comment by supergarotinho** [comment]
The error continues:

ActionView::TemplateError (undefined method `checked_image' for #ActionView::Base:0xb686f1f8) on line #21 of vendor/plugins/redmine_menu_links/app/views/menu_links/index.html.erb:
18:   <tr class="<%= cycle("odd", "even") %>">
19:   <td align="center"><%= link_to link.name, link.url, {:target => link.new_window ? '_blank' : nil} %></td>
20:   <td align="center"><%= link.for_everyone? ? l(:label_everyone) : (link.for_users_only? ? l(:label_users_only) : l(:label_administrators_only)) %></td>
21:   <td align="center"><%= checked_image link.is_enabled %></td>
22:   <td align="center"><%= checked_image link.new_window %></td>
23:   <td align="center" style="width:15%;"><%= reorder_links('menu_link', {:action => 'update', :id => link}) %></td>
24:   <td class="buttons">

**Comment by supergarotinho** [comment]
Im using Redmine 0.9.X

**Comment by Tide** [comment]
I will look into this.  checked_image is something that is default in Redmine.  I am just using it as well.  Thanks for the input I will see what I can find.

**Comment by Tide** [comment]
Go to app/helpers/application_helper.rb and look around line 700.  Do you have a definition for checked_image like below?

<pre>
  def checked_image(checked=true)
    if checked
      image_tag 'toggle_check.png'
    end
  end
</pre>

**Comment by supergarotinho** [comment]
his function does not exists on this file.

**Comment by Tide** [comment]
Which version of Redmine are you using exactly?

**Comment by supergarotinho** [comment]
Redmine 0.9.3.stable.3625

**Comment by Tide** [comment]
That is odd.  Check again to make sure.  Here is the file at the Redmine site http://www.redmine.org/projects/redmine/repository/revisions/3625/entry/trunk/app/helpers/application_helper.rb look at line 700.

**Comment by supergarotinho** [comment]
I have downloaded redmine again and solved.

Thanks!

**Comment by Tide** [comment]
Glad to hear it!
