### ISSUE TITLE
Error migrating using Redmine 2.3.1

### ISSUE THREAD

**Issue by spragucm** [Tide/redmine_menu_links#5]
Hello,
I tried to install this plugin for Redmine 2.3.1 and received the message below after using rake redmine:plugins:migrate RAIL_ENV=production

rake aborted!
uninitialized constant RAILS_DEFAULT_LOGGER

Could this be fixed so that the plugin works with Redmine 2.3.1?

**Comment by spragucm** [comment]
Out of curiosity, why was this closed? Does it work and I'm just not using it correctly?

Never mind...I just uploaded the new version and it works great.

Thanks for a wonderful plugin and fast response!

**Comment by Tide** [comment]
Hey,

Sorry I hit ht e wrong button.  I meant to reply that it is updated and
should work now on Redmine 2.x.x and then close it.  It is funny you
emailed me I was just sitting down to email you that it had been updated.

Best of luck,
Tide
