### ISSUE TITLE
More links

### ISSUE THREAD

**Issue by balagab** [Tide/redmine_menu_links#9]
Can I add more links? If yes, how? Thanks

**Comment by Tide** [comment]
Go to the admin section and click on the menu links icon.

**Comment by balagab** [comment]
:)
I know where can I add a link (admin->plugins->Menu link) my question was how can I add more links? So I would like to add 2-3 menu to the top menu.
Thanks

**Comment by Tide** [comment]
Are you using https://github.com/Tide/menu_link or https://github.com/Tide/redmine_menu_links.  It sounds like you are using menu_link but posting in the menu_links repo.

If you are using menu_links then there is a button to add as many links as you would like at the top of the admin page.  

If you are using menu_link (the old one), then you can add only one link.

**Comment by balagab** [comment]
Thank you, that’s it! ☺

**Comment by Tide** [comment]
Glad to help.
